### ISSUE TITLE
Warning at boot

### ISSUE THREAD

**Issue by moul** [scaleway/image-alpine#11]
```
* Fetching SSH keys .../usr/local/sbin/oc-fetch-ssh-keys: line 13: [: ==: unary operator expected
```

**Comment by nulani** [comment]
I got rid of the warning by changing `if [ $1 == "--upgrade" ]; then` to `if [[ $1 == "--upgrade" ]]; then`.

**Comment by moul** [comment]
Hi @nulani, thanks for your feedback :)

We fixed it in the common scripts repository: https://github.com/scaleway/image-tools/pull/72
