### ISSUE TITLE
Fetching SSH keys failure

### ISSUE THREAD

**Issue by zx2c4** [scaleway/image-alpine#16]
When running setup-alpine after first boot, the following occurs:

    * Fetching SSH keys ...
    /usr/local/sbin/oc-fetch-ssh-keys: line 13: [: ==: unary operator expected

**Comment by moul** [comment]
Hi @zx2c4,

This was fixed with https://github.com/scaleway/image-tools/commit/508e5113f3ed2191a7be2d82ec86b56f8a7341d1
I though we rebuilt this image, but apparently not

We will rebuild this image soon, for now you can hotfix using

```console
$ wget https://raw.githubusercontent.com/scaleway/image-tools/master/skeleton-common/usr/local/sbin/oc-fetch-ssh-keys -O /usr/local/sbin/oc-fetch-ssh-keys
```

**Comment by moul** [comment]
A new version of the image was just released with this patch

https://cloud.scaleway.com/#/servers/new?image=0db40856-df11-40b4-b09e-53606d025f95

**Comment by moul** [comment]
@zx2c4 the new image fetches the keys correctly, but another but was introduced, sorry if you have a ⚠️ about .ssh/authorized_keys

**Comment by moul** [comment]
A new image is actually building: https://github.com/scaleway/qa/pull/117

**Comment by moul** [comment]
This one is tested and works as expected: https://cloud.scaleway.com/#/servers/new?image=ac8dd82d-278c-4a96-85aa-11cf6eb7800c

**Comment by moul** [comment]
A new image was released here with the fix: http://devhub.scaleway.com/#/images/alpine:latest

**Comment by moul** [comment]
Closing this issue, do not hesitate to reopen it if you still encounter a problem
