### ISSUE TITLE
Kernel modules are not available

### ISSUE THREAD

**Issue by vincentvdk** [scaleway/image-alpine#17]
See this topic : https://community.scaleway.com/t/iptables-on-alpine-linux/1555

**Comment by moul** [comment]
We need to add an init script that calls `ok-fetch-kernel-modules`

**Comment by moul** [comment]
@vincentvdk as you can see in #18, you can just run the following command: `rc-update add sync-kernel-extra default`.

This patch will be available with the next build of this image

**Comment by vincentvdk** [comment]
@moul yeah, fixed it myself that way. Thanks for fixing \o/
