### ISSUE TITLE
su: must be suid to work properly

### ISSUE THREAD

**Issue by ScrumpyJack** [scaleway/image-alpine#19]
there was a problem with bbsuid in the busybox package that stopped su working.
This can be fixed by updating the bbsuid binary with apk add busybox-suid
Can you add the busybox-suid to the default packages that are pulled into image-alpine?

**Comment by moul** [comment]
Hi @ScrumpyJack, thank you for your feedback,

I created the PR #20, with `busybox-suid` added by default, as soon as the PR is merged, we will rebuild the image and test if everything seems OK

**Comment by Drugoy** [comment]
It is still not added to alpine images of older versions (like 3.5, 3.4).

**Comment by paddedwith0s** [comment]
i see the same happening in Alpine 3.8 lxd container
