### ISSUE TITLE
Update to 3.3

### ISSUE THREAD

**Issue by matunixe** [scaleway/image-alpine#21]
Hello there,
Can you update the image? There is a lot of major changes with the last version !
Cheers,

**Comment by moul** [comment]
Hi @matunixe, thank you for your feedback, I will try to get this running on C1 servers

**Comment by matunixe** [comment]
Some of the new features are:

- linux 4.1 kernel
- gcc 5.3.0 / musl 1.1.12
-New repository named community
- mariadb 10.1
- Xen 4.6
- perl 5.22
- isohybrid boot images
- refactored initramfs. alpine_dev boot option no longer needed and better support for cryptroot, lvm, madam

Complete changes: http://git.alpinelinux.org/cgit/aports/log/?h=v3.3.0

**Comment by moul** [comment]
Ok good, I succeed to build the image, I need to give some last fixes before pushing it, it will be done today

Note that:
- Linux 4.1 kernel -> actually you will get a 4.3 kernel instead
- Xen -> I think that the C1 server won't support most of the Xen features, i.e: no Intel VT instructions
- We are using our own [initrd](https://github.com/scaleway/initrd/tree/master/Linux), we already took care of not needing `alpine_dev` :) but we are actually missing `cryptroot`, `lvm` & `madam` support, are you using one of the last 3 features ? if so, you can follow [this issue](https://github.com/scaleway/initrd/issues/12) or just explain here your usage, so we can increase the priority of one of the feature and better understand how you want to use this :)

**Comment by moul** [comment]
The image is now public

http://devhub.scaleway.com/#/images/alpine:latest

**Comment by moul** [comment]
Closing this issue, do not hesitate to reopen it or create a new one if you encounter any problems with the new image

**Comment by matunixe** [comment]
I just try the new image, works great. Thanks @moul !
