### ISSUE TITLE
Can't format new volume

### ISSUE THREAD

**Issue by matunixe** [scaleway/image-alpine#31]
Hello,

The procedure described [here](https://www.scaleway.com/docs/attach-and-detach-a-volume-to-an-existing-server/#-Step-3--Format-the-additional-volume) doesn't work because unavailability of mkfs.ext4. 
```
~# mkfs -t ext4 /dev/nbd1
mkfs: failed to execute mkfs.ext4: No such file or directory
```

Only the followings filesystems are supported:
```
~# mkfs.
mkfs.bfs     mkfs.cramfs  mkfs.minix   mkfs.vfat
```

I won't use brainfuck filesystem, what can I do ? :(

**Comment by QuentinPerez** [comment]
Hi @matunixe 

Can try to install `e2fsprogs mkinitfs` before `mkfs -t ext4 /dev/nbd1` ?
```
apk update && apk add e2fsprogs mkinitfs
```
let me know if you have any questions.

**Comment by matunixe** [comment]
It works flawless.

Many thanks sir!
