### ISSUE TITLE
tmp directory

### ISSUE THREAD

**Issue by QuentinPerez** [scaleway/image-alpine#34]
Check if tmp directory is a tmpfs

**Comment by halmartin** [comment]
@QuentinPerez Sorry, I don't really understand this issue.

The default behaviour of Alpine Linux is not to mount `/tmp` as `/tmpfs`

If you want to use a `tmpfs` for `/tmp` you can enable it yourself in `/etc/fstab`:

```
$ echo "tmpfs /tmp tmpfs rw,nosuid,nodev" | sudo tee -a /etc/fstab
$ sudo reboot
```

After rebooting, `/tmp` will be mounted as `tmpfs`:

```
$ mount | grep /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime)
```

As this is not the distribution default, we will leave it to users to implement this change.

---

If I have incorrectly understood this issue, please let me know.
