### ISSUE TITLE
sh(1) (ash) compliant script

### ISSUE THREAD

**Issue by Ypnose** [scaleway/image-alpine#36]
Hi there,
Many scripts seem to use <code>/bin/bash</code>, even for the simple scripts (as for <code>scw-nbd-disconnect-root</code> or <code>oc-generate-ssh-keys</code>). After a quick review, bashisms are not often used. Do you plan to modify them to make them fully <code>ash</code> compliant? That could allow people to not have <code>bash</code> in the minimal instances.
I'm ready to give a hand if you need / want it.

**Comment by moul** [comment]
Hi @Ypnose, #37 should fit your needs :)

**Comment by Ypnose** [comment]
@moul Thank you for your work! :godmode:
I have two other questions: you modified the script, <code>bash</code> could be also removed in the <code>Dockerfile</code>, or I am wrong?
Do you know when the updated image will be avaible on Scaleway?

**Comment by moul** [comment]
> @moul Thank you for your work! :godmode:

Credits are for @muhmuhten (https://github.com/scaleway/image-tools/pull/172), I only synced its modifications on this repo

> bash could be also removed in the Dockerfile

yes we can remove it from the Dockerfile, do you want to do the PR ? (You don't need to setup all the build stuff, just remove the line, it will works :p)

> Do you know when the updated image will be avaible on Scaleway? :)

@QuentinPerez will release the next version of this image, it can be done on monday

**Comment by Ypnose** [comment]
I'm really busy ATM @moul. Will try to do the tiny PR this weekend.
