### ISSUE TITLE
run with IPv6 only

### ISSUE THREAD

**Issue by ghartz** [scaleway/image-alpine#46]
Hi !

When starting an alpine image with an ipv6 only, the instance never ping.
ex:
scw run --ipv6 --ip-address="none" alpine-linux

The same command with an ubuntu and the instance pings back as expected. This also behavior occurs with the  web ui as well.

A "scw inspect <instance>" returns the ipv6 attached to the instance.

**Comment by QuentinPerez** [comment]
Did you follow the command that you can found here https://blog.online.net/2016/03/31/introducing-native-ipv6-connectivity-on-scaleway/ to enable ipv6

**Comment by ghartz** [comment]
How I'm supposed to enable ipv6 if the instance doesn't ping on Internet? By it's private ip throught another instance having a public ipv4 ? By enabling an ipv4, configuring ipv6 then removing it ?

With "scw run --ipv6 --ip-address="none" ubuntu", the instance ping on its ipv6 address but when it comes to an alpine image, it doesn't.

What is expected is that the alpine image at startup configure it's ipv6 by itself as the ubuntu image already does.

**Comment by halmartin** [comment]
@ghartz I have tested this scenario on the Alpine 3.7 image we released this week.

If I understand your issue correctly, you are trying to do the following:
  1. Create an Alpine instance without a public IPv4 address
  1. Use only IPv6 networking

From the behaviour you've witnessed:
  1. You create the instance, but cannot access it via the public IPv6 address

If I have understood the scenario incorrectly, please let me know.

I have just tested this with the Alpine 3.7 `VC1` **local boot** image, and the scenario you describe is working.

I am able to create the VM without a public IPv4 address and access it via the public IPv6 address.

Please let me know if you experience any issues.
