### ISSUE TITLE
GRSEC kernel?

### ISSUE THREAD

**Issue by dodedodo** [scaleway/image-alpine#47]
Will GRSEC be supported anywhere in the near future? It's one of the main selling points of alpine.

**Comment by halmartin** [comment]
@dodedodo better late than never, I guess :slightly_smiling_face: 

Our new local boot feature allows booting a distribution kernel. We will very shortly (<1 week) have an Alpine image for local booting (on VC1 only) that ships with the linux-hardened grsec kernel.

If you can't wait, you can build the image yourself off my branch: https://github.com/scaleway/image-alpine/pull/58

**Comment by halmartin** [comment]
`VC1` images using local boot are now using the `linux-hardened` kernel by default. This is the grsec kernel available from Alpine Linux repositories.
