### ISSUE TITLE
Please update to 3.5.0

### ISSUE THREAD

**Issue by matunixe** [scaleway/image-alpine#48]
Hello,

As said in the title please update the Alpine Linux image to 3.5.0, there is a lot of changes since the last one:

- Change from OpenSSL to LibreSSL
- Add ZFS root support
- ...

You can find more about this on the [release announcement](https://www.alpinelinux.org/posts/Alpine-3.5.0-released.html)

Thanks in advance.

**Comment by moul** [comment]
Hi @matunixe, see #49

**Comment by matunixe** [comment]
Hey @moul , many thanks !
