### ISSUE TITLE
git clone not doing anything

### ISSUE THREAD

**Issue by nozel** [scaleway/image-alpine#50]
I am using the alpine 3.3 image on my c2l instance and when I use:
```bash
git clone any_repository
```
Where ```any_repository``` was substituted by numerous repositories (i.e., github, bitbucket, gitlab). It says ```Cloning into 'any_repository'...``` but no repo is being downloaded or created. Am I missing something obvious? ```git init``` seems to work fine.

Cheers!

**Comment by moul** [comment]
Hi @nozel 

Is `any_repository` the real argument? Because as far as I know, the argument next to clone should always be a URI (https URL, git URI, or path)

**Comment by nozel** [comment]
Thank you for the reply. I clarified my question. ```any_repository``` was meant as a variable.

**Comment by moul** [comment]
OK, as it I've no idea; maybe you should catch Alpine Linux developers and communities on IRC, sometimes Alpine provides lighten versions of software, and sometimes this means removing some features or behaviors

**Comment by nozel** [comment]
Thank you for the suggestion, but ```git clone``` is basic functionality, which I cannot imagine Alpine would remove. To verify this I tested this in an Alpine 3.3 docker container locally on my Mac.

On my scaleway instance I only added docker since I only want to run containers so in my running Alpine container on my Mac I installed docker which depends on git.  ```git clone``` works as expected.

Strangely, cloning Alpine repositories did work on my scaleway instance. That's why I think this is an issue related to this image.

Anyway, I solved the problem, albeit with some hiccups. I did ```apk upgrade git``` which gave a lot of errors after a ```git clone``` like:

```
Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/lib/libcurl.so.4)
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /usr/lib/libcurl.so.4)
Error relocating /usr/lib/libcurl.so.4: SSL_get_error: symbol not found
...
```

I tried to delete git, but this was not possible since docker was depending on it. Anyway my sequence was:
```
juggernaut:~# apk del git
World updated, but the following packages are not removed due to:
  git: docker

(1/2) Installing libcrypto1.0 (1.0.2j-r2)
(2/2) Installing libssl1.0 (1.0.2j-r2)
1 errors; 186 MiB in 52 packages
juggernaut:~# apk add git
1 errors; 186 MiB in 52 packages
juggernaut:~# apk update git
fetch http://nl.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/edge/community/x86_64/APKINDEX.tar.gz
v3.5.0-4-gc5011b05c8 [http://nl.alpinelinux.org/alpine/latest-stable/main]
v3.5.0-119-g9ac88f9260 [http://mirror1.hs-esslingen.de/pub/Mirrors/alpine/edge/community]
OK: 7956 distinct packages available
juggernaut:~# apk upgrade git
(1/4) Installing libcurl (7.52.1-r0)
(2/4) Upgrading curl (7.47.0-r0 -> 7.52.1-r0)
(3/4) Purging libssl1.0 (1.0.2j-r2)
(4/4) Purging libcrypto1.0 (1.0.2j-r2)
Executing busybox-1.25.1-r0.trigger
1 errors; 183 MiB in 51 packages
````

Although there supposedly is an error, I can use ```git clone``` properly. Maybe it can help someone else.

Cheers!

**Comment by micahlmartin** [comment]
@nozel I think the trick is in the `apk upgrade`. I was having the same issue and then after upgrading the system packages it started working.

**Comment by halmartin** [comment]
I just created a new `VC1` instance with our updated Aline Linux 3.7 image and tested this:

```
scw-5c9d6e:~# apk add git
fetch http://nl.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
(1/3) Installing expat (2.2.5-r0)
(2/3) Installing pcre2 (10.30-r0)
(3/3) Installing git (2.15.0-r1)
Executing busybox-1.27.2-r8.trigger
OK: 559 MiB in 70 packages
scw-5c9d6e:~# git clone https://github.com/scaleway/image-alpine.git
Cloning into 'image-alpine'...
remote: Counting objects: 531, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 531 (delta 0), reused 4 (delta 0), pack-reused 524
Receiving objects: 100% (531/531), 1.13 MiB | 2.71 MiB/s, done.
Resolving deltas: 100% (225/225), done.
```

Please let me know if you have created a new instance with Alpine Linux 3.7 and are still having difficulties cloning a git repository (such as this one).
