### ISSUE TITLE
Alpine Linux on Scaleway ARM64 VPS (ARMv8 SSD Cloud Servers)

### ISSUE THREAD

**Issue by ogoudron** [scaleway/image-alpine#57]
Hello,
Does someone can tell me why Scaleway do not provide Alpine Linux on their ARMv8 SSD Cloud Servers ?
Is it because it does not work ?
Can i install it by himself ?

I would really like to use Alpine Linux on Scaleway ARMv8 servers because i use it on C1 and all X86 variants.

Bests regards, Olivier.

**Comment by PHPoenX** [comment]
ARMv8 has architecture named "aarch64"
